version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lmsdb
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lms-network

  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lms-app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lmsdb
      SPRING_DATASOURCE_USERNAME: lms_user
      SPRING_DATASOURCE_PASSWORD: lms_password
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: mySecretKey123456789012345678901234567890
      JWT_EXPIRATION: 86400000
    networks:
      - lms-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  lms-network:
    driver: bridge
